"""Configuration management for Valkey server."""

from pathlib import Path
from typing import Any

from .exceptions import ValkeyConfigurationError

# Default configuration optimized for testing and development
DEFAULT_CONFIG: dict[str, Any] = {
    "bind": "127.0.0.1",
    "protected-mode": "yes",
    "daemonize": "no",
    "save": "",  # Disable RDB snapshots
    "appendonly": "no",  # Disable AOF
    "logfile": "",  # Log to stdout
    "loglevel": "notice",
}


def generate_config_file(
    config_path: Path,
    port: int,
    data_dir: Path,
    config_overrides: dict[str, Any],
) -> None:
    """
    Generate a Valkey configuration file.

    Args:
        config_path: Path where the config file will be written
        port: Port number for the server
        data_dir: Directory for Valkey data files
        config_overrides: User-provided configuration overrides

    Raises:
        IOError: If config file cannot be written
    """
    # Start with defaults
    config = DEFAULT_CONFIG.copy()

    # Add runtime values
    config["port"] = str(port)
    config["dir"] = str(data_dir)

    # Apply user overrides
    config.update(config_overrides)

    # Generate config file content
    lines = []
    lines.append("# Valkey configuration generated by valkey-server")
    lines.append("# https://github.com/cyborginc/valkey-server-py")
    lines.append("")

    for key, value in config.items():
        if value == "":
            # Empty string means disable the option
            # e.g., "save" "" disables RDB
            lines.append(f'{key} ""')
        elif isinstance(value, bool):
            # Convert Python bool to Valkey yes/no
            lines.append(f"{key} {'yes' if value else 'no'}")
        elif isinstance(value, list | tuple):
            # Multiple values (e.g., save 900 1 300 10)
            values_str = " ".join(str(v) for v in value)
            lines.append(f"{key} {values_str}")
        else:
            lines.append(f"{key} {value}")

    # Write config file
    config_content = "\n".join(lines) + "\n"
    config_path.write_text(config_content, encoding="utf-8")


def validate_config(config: dict[str, Any]) -> None:
    """
    Validate configuration options.

    Args:
        config: Configuration dictionary to validate

    Raises:
        ValkeyConfigurationError: If configuration is invalid
    """
    # Validate bind address
    if "bind" in config:
        bind_value = config["bind"]
        if bind_value == "0.0.0.0":
            raise ValkeyConfigurationError(
                "Binding to 0.0.0.0 is discouraged for security reasons. "
                "Use 127.0.0.1 for localhost only, or specify an explicit IP address."
            )

    # Warn about daemonize
    if config.get("daemonize") == "yes":
        raise ValkeyConfigurationError(
            "daemonize=yes is not supported by valkey-server. "
            "The server must run in foreground mode for proper process management."
        )

    # Validate port
    if "port" in config:
        port = config["port"]
        if isinstance(port, int) and not 1 <= port <= 65535:
            raise ValkeyConfigurationError(f"Invalid port number: {port}. Must be 1-65535.")
